env:
  es2020: true

ignorePatterns:
  - dist

extends:
  - plugin:@lichtblick/base

overrides:
  - files: ["*.ts", "*.tsx"]
    extends:
      - plugin:@lichtblick/typescript
    parserOptions:
      project: ./tsconfig.json
